=== moreal/9c-market/public/data/network.prices.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "priceInfo": {
      "type": "object",
      "properties": {
        "KRW": {
          "type": "number"
        },
        "USD": {
          "type": "number"
        }
      }
    }
  },
  "properties": {
    "Hourglass 3000": {
      "type": "object",
      "$ref": "#/definitions/priceInfo"
    },
    "Hourglass 15000": {
      "type": "object",
      "$ref": "#/definitions/priceInfo"
    },
    "Hourglass 30000": {
      "type": "object",
      "$ref": "#/definitions/priceInfo"
    },
    "AP Potion 15": {
      "type": "object",
      "$ref": "#/definitions/priceInfo"
    },
    "AP Potion 75": {
      "type": "object",
      "$ref": "#/definitions/priceInfo"
    },
    "AP Potion 150": {
      "type": "object",
      "$ref": "#/definitions/priceInfo"
    },
    "20 Golden Dust": {
      "type": "object",
      "$ref": "#/definitions/priceInfo"
    },
    "100 Golden Dust": {
      "type": "object",
      "$ref": "#/definitions/priceInfo"
    },
    "200 Golden Dust": {
      "type": "object",
      "$ref": "#/definitions/priceInfo"
    },
    "600 Golden Dust": {
      "type": "object",
      "$ref": "#/definitions/priceInfo"
    }
  },
  "required": [
    "Hourglass 3000",
    "Hourglass 15000",
    "Hourglass 30000",
    "AP Potion 15",
    "AP Potion 75",
    "AP Potion 150",
    "20 Golden Dust",
    "100 Golden Dust",
    "200 Golden Dust",
    "600 Golden Dust"
  ]
}

=== moreal/9c-market/public/data/heimdall.prices.json
{
	"Hourglass 3000": {
		"KRW": 4400
	},
	"Hourglass 15000": {
		"KRW": 22000
	},
	"Hourglass 30000": {
		"KRW": 44000
	},
	"AP Potion 15": {
		"KRW": 4400
	},
	"AP Potion 75": {
		"KRW": 22000
	},
	"AP Potion 150": {
		"KRW": 44000
	},
	"20 Golden Dust": {
		"KRW": 4400
	},
	"100 Golden Dust": {
		"KRW": 22000
	},
	"200 Golden Dust": {
		"KRW": 44000
	},
	"600 Golden Dust": {
		"KRW": 129000
	}
}
